# Generated by carnix 0.9.8: /home/leo60228/.nix-profile/bin/cargo-generate-nixfile generate-nixfile --standalone --src .
with import <nixpkgs> {};
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
  cratesIO = (callPackage ./crates-io.nix { });
in
rec {
  crates = cratesIO // rec {
# perf-checkup-0.1.0

    crates.perf_checkup."0.1.0" = deps: { features?(features_.perf_checkup."0.1.0" deps {}) }: buildRustCrate {
      crateName = "perf-checkup";
      version = "0.1.0";
      authors = [ "leo60228 <iakornfeld@gmail.com>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      dependencies = mapFeatures features ([
        (cratesIO.crates."derive_more"."${deps."perf_checkup"."0.1.0"."derive_more"}" deps)
        (cratesIO.crates."futures_preview"."${deps."perf_checkup"."0.1.0"."futures_preview"}" deps)
        (cratesIO.crates."heim"."${deps."perf_checkup"."0.1.0"."heim"}" deps)
        (cratesIO.crates."lazy_static"."${deps."perf_checkup"."0.1.0"."lazy_static"}" deps)
        (cratesIO.crates."notify_rust"."${deps."perf_checkup"."0.1.0"."notify_rust"}" deps)
        (cratesIO.crates."regex"."${deps."perf_checkup"."0.1.0"."regex"}" deps)
        (cratesIO.crates."runtime"."${deps."perf_checkup"."0.1.0"."runtime"}" deps)
        (cratesIO.crates."snafu"."${deps."perf_checkup"."0.1.0"."snafu"}" deps)
      ]);
    };
    features_.perf_checkup."0.1.0" = deps: f: updateFeatures f (rec {
      derive_more."${deps.perf_checkup."0.1.0".derive_more}".default = true;
      futures_preview."${deps.perf_checkup."0.1.0".futures_preview}".default = true;
      heim."${deps.perf_checkup."0.1.0".heim}".default = true;
      lazy_static."${deps.perf_checkup."0.1.0".lazy_static}".default = true;
      notify_rust."${deps.perf_checkup."0.1.0".notify_rust}".default = true;
      perf_checkup."0.1.0".default = (f.perf_checkup."0.1.0".default or true);
      regex."${deps.perf_checkup."0.1.0".regex}".default = true;
      runtime."${deps.perf_checkup."0.1.0".runtime}".default = true;
      snafu."${deps.perf_checkup."0.1.0".snafu}".default = true;
    }) [
      (cratesIO.features_.derive_more."${deps."perf_checkup"."0.1.0"."derive_more"}" deps)
      (cratesIO.features_.futures_preview."${deps."perf_checkup"."0.1.0"."futures_preview"}" deps)
      (cratesIO.features_.heim."${deps."perf_checkup"."0.1.0"."heim"}" deps)
      (cratesIO.features_.lazy_static."${deps."perf_checkup"."0.1.0"."lazy_static"}" deps)
      (cratesIO.features_.notify_rust."${deps."perf_checkup"."0.1.0"."notify_rust"}" deps)
      (cratesIO.features_.regex."${deps."perf_checkup"."0.1.0"."regex"}" deps)
      (cratesIO.features_.runtime."${deps."perf_checkup"."0.1.0"."runtime"}" deps)
      (cratesIO.features_.snafu."${deps."perf_checkup"."0.1.0"."snafu"}" deps)
    ];


# end

  };

  perf_checkup = crates.crates.perf_checkup."0.1.0" deps;
  __all = [ (perf_checkup {}) ];
  deps.aho_corasick."0.7.4" = {
    memchr = "2.2.1";
  };
  deps.argon2rs."0.2.5" = {
    blake2_rfc = "0.2.18";
    scoped_threadpool = "0.1.9";
  };
  deps.arrayvec."0.4.11" = {
    nodrop = "0.1.13";
  };
  deps.async_datagram."2.2.0" = {};
  deps.async_datagram."3.0.0" = {};
  deps.async_ready."3.0.0" = {};
  deps.autocfg."0.1.5" = {};
  deps.backtrace."0.3.33" = {
    backtrace_sys = "0.1.31";
    cfg_if = "0.1.9";
    libc = "0.2.60";
    rustc_demangle = "0.1.15";
  };
  deps.backtrace_sys."0.1.31" = {
    libc = "0.2.60";
    cc = "1.0.38";
  };
  deps.bitflags."1.1.0" = {};
  deps.blake2_rfc."0.2.18" = {
    arrayvec = "0.4.11";
    constant_time_eq = "0.1.3";
  };
  deps.block."0.1.6" = {};
  deps.bumpalo."2.5.0" = {};
  deps.cc."1.0.38" = {};
  deps.cfg_if."0.1.9" = {};
  deps.chrono."0.4.7" = {
    libc = "0.2.60";
    num_integer = "0.1.41";
    num_traits = "0.2.8";
    time = "0.1.42";
  };
  deps.cloudabi."0.0.3" = {
    bitflags = "1.1.0";
  };
  deps.constant_time_eq."0.1.3" = {};
  deps.core_foundation."0.6.4" = {
    core_foundation_sys = "0.6.2";
    libc = "0.2.60";
  };
  deps.core_foundation_sys."0.6.2" = {};
  deps.crossbeam."0.6.0" = {
    cfg_if = "0.1.9";
    crossbeam_channel = "0.3.9";
    crossbeam_deque = "0.6.3";
    crossbeam_epoch = "0.7.2";
    crossbeam_utils = "0.6.6";
    lazy_static = "1.3.0";
    num_cpus = "1.10.1";
    parking_lot = "0.7.1";
  };
  deps.crossbeam_channel."0.3.9" = {
    crossbeam_utils = "0.6.6";
  };
  deps.crossbeam_deque."0.6.3" = {
    crossbeam_epoch = "0.7.2";
    crossbeam_utils = "0.6.6";
  };
  deps.crossbeam_epoch."0.7.2" = {
    arrayvec = "0.4.11";
    cfg_if = "0.1.9";
    crossbeam_utils = "0.6.6";
    lazy_static = "1.3.0";
    memoffset = "0.5.1";
    scopeguard = "1.0.0";
  };
  deps.crossbeam_utils."0.6.6" = {
    cfg_if = "0.1.9";
    lazy_static = "1.3.0";
  };
  deps.dbus."0.6.5" = {
    libc = "0.2.60";
    libdbus_sys = "0.2.0";
  };
  deps.derive_more."0.15.0" = {
    lazy_static = "1.3.0";
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    regex = "1.2.0";
    syn = "0.15.42";
    rustc_version = "0.2.3";
  };
  deps.dirs."1.0.5" = {
    redox_users = "0.3.0";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.doc_comment."0.3.1" = {};
  deps.failure."0.1.5" = {
    backtrace = "0.3.33";
    failure_derive = "0.1.5";
  };
  deps.failure_derive."0.1.5" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
    synstructure = "0.10.2";
  };
  deps.fuchsia_cprng."0.1.1" = {};
  deps.fuchsia_zircon."0.3.3" = {
    bitflags = "1.1.0";
    fuchsia_zircon_sys = "0.3.3";
  };
  deps.fuchsia_zircon_sys."0.3.3" = {};
  deps.futures."0.1.28" = {};
  deps.futures_channel_preview."0.3.0-alpha.17" = {
    futures_core_preview = "0.3.0-alpha.17";
    futures_sink_preview = "0.3.0-alpha.17";
  };
  deps.futures_core_preview."0.3.0-alpha.17" = {};
  deps.futures_executor_preview."0.3.0-alpha.17" = {
    futures_channel_preview = "0.3.0-alpha.17";
    futures_core_preview = "0.3.0-alpha.17";
    futures_util_preview = "0.3.0-alpha.17";
    num_cpus = "1.10.1";
  };
  deps.futures_io_preview."0.3.0-alpha.17" = {};
  deps.futures_preview."0.3.0-alpha.17" = {
    futures_channel_preview = "0.3.0-alpha.17";
    futures_core_preview = "0.3.0-alpha.17";
    futures_executor_preview = "0.3.0-alpha.17";
    futures_io_preview = "0.3.0-alpha.17";
    futures_sink_preview = "0.3.0-alpha.17";
    futures_util_preview = "0.3.0-alpha.17";
  };
  deps.futures_sink_preview."0.3.0-alpha.17" = {
    futures_core_preview = "0.3.0-alpha.17";
  };
  deps.futures_timer."0.2.1" = {
    futures_preview = "0.3.0-alpha.17";
    pin_utils = "0.1.0-alpha.4";
  };
  deps.futures_util_preview."0.3.0-alpha.17" = {
    futures_channel_preview = "0.3.0-alpha.17";
    futures_core_preview = "0.3.0-alpha.17";
    futures_io_preview = "0.3.0-alpha.17";
    futures_sink_preview = "0.3.0-alpha.17";
    memchr = "2.2.1";
    pin_utils = "0.1.0-alpha.4";
    slab = "0.4.2";
  };
  deps.glob."0.3.0" = {};
  deps.heim."0.0.5" = {
    heim_common = "0.0.5";
    heim_cpu = "0.0.5";
    heim_derive = "0.0.5";
    heim_disk = "0.0.5";
    heim_host = "0.0.5";
    heim_memory = "0.0.5";
    heim_net = "0.0.5";
    heim_process = "0.0.5";
    heim_virt = "0.0.5";
  };
  deps.heim_common."0.0.5" = {
    cfg_if = "0.1.9";
    futures_preview = "0.3.0-alpha.17";
    heim_derive = "0.0.5";
    core_foundation = "0.6.4";
    mach = "0.3.2";
    winapi = "0.3.7";
    libc = "0.2.60";
    nix = "0.14.1";
  };
  deps.heim_cpu."0.0.5" = {
    cfg_if = "0.1.9";
    heim_common = "0.0.5";
    heim_derive = "0.0.5";
    lazy_static = "1.3.0";
    glob = "0.3.0";
    libc = "0.2.60";
    mach = "0.3.2";
    winapi = "0.3.7";
  };
  deps.heim_derive."0.0.5" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
  };
  deps.heim_disk."0.0.5" = {
    bitflags = "1.1.0";
    cfg_if = "0.1.9";
    heim_common = "0.0.5";
    heim_derive = "0.0.5";
    core_foundation = "0.6.4";
    mach = "0.3.2";
    widestring = "0.4.0";
    winapi = "0.3.7";
    libc = "0.2.60";
  };
  deps.heim_host."0.0.5" = {
    cfg_if = "0.1.9";
    heim_common = "0.0.5";
    heim_derive = "0.0.5";
    libc = "0.2.60";
    platforms = "0.2.0";
    lazy_static = "1.3.0";
    mach = "0.3.2";
    winapi = "0.3.7";
  };
  deps.heim_memory."0.0.5" = {
    cfg_if = "0.1.9";
    heim_common = "0.0.5";
    heim_derive = "0.0.5";
    lazy_static = "1.3.0";
    libc = "0.2.60";
    mach = "0.3.2";
    winapi = "0.3.7";
  };
  deps.heim_net."0.0.5" = {
    bitflags = "1.1.0";
    cfg_if = "0.1.9";
    heim_common = "0.0.5";
    heim_derive = "0.0.5";
    libc = "0.2.60";
    macaddr = "0.1.1";
    hex = "0.3.2";
    nix = "0.14.1";
  };
  deps.heim_process."0.0.5" = {
    cfg_if = "0.1.9";
    heim_common = "0.0.5";
    heim_derive = "0.0.5";
    libc = "0.2.60";
    mach = "0.3.2";
    winapi = "0.3.7";
  };
  deps.heim_virt."0.0.5" = {
    cfg_if = "0.1.9";
    heim_common = "0.0.5";
    raw_cpuid = "6.1.0";
  };
  deps.hex."0.3.2" = {};
  deps.iovec."0.1.2" = {
    libc = "0.2.60";
    winapi = "0.2.8";
  };
  deps.js_sys."0.3.25" = {
    wasm_bindgen = "0.2.48";
  };
  deps.juliex."0.3.0-alpha.7" = {
    crossbeam = "0.6.0";
    futures_preview = "0.3.0-alpha.17";
    lazy_static = "1.3.0";
    num_cpus = "1.10.1";
  };
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.lazy_static."1.3.0" = {};
  deps.libc."0.2.60" = {};
  deps.libdbus_sys."0.2.0" = {
    pkg_config = "0.3.14";
  };
  deps.lock_api."0.1.5" = {
    owning_ref = "0.4.0";
    scopeguard = "0.3.3";
  };
  deps.log."0.4.7" = {
    cfg_if = "0.1.9";
  };
  deps.mac_notification_sys."0.3.0" = {
    chrono = "0.4.7";
    dirs = "1.0.5";
    objc_foundation = "0.1.1";
    cc = "1.0.38";
  };
  deps.macaddr."0.1.1" = {};
  deps.mach."0.3.2" = {
    libc = "0.2.60";
  };
  deps.malloc_buf."0.0.6" = {
    libc = "0.2.60";
  };
  deps.memchr."2.2.1" = {};
  deps.memoffset."0.5.1" = {
    rustc_version = "0.2.3";
  };
  deps.mio."0.6.19" = {
    iovec = "0.1.2";
    log = "0.4.7";
    net2 = "0.2.33";
    slab = "0.4.2";
    fuchsia_zircon = "0.3.3";
    fuchsia_zircon_sys = "0.3.3";
    libc = "0.2.60";
    kernel32_sys = "0.2.2";
    miow = "0.2.1";
    winapi = "0.2.8";
  };
  deps.mio_uds."0.6.7" = {
    iovec = "0.1.2";
    libc = "0.2.60";
    mio = "0.6.19";
  };
  deps.miow."0.2.1" = {
    kernel32_sys = "0.2.2";
    net2 = "0.2.33";
    winapi = "0.2.8";
    ws2_32_sys = "0.2.1";
  };
  deps.net2."0.2.33" = {
    cfg_if = "0.1.9";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.nix."0.14.1" = {
    bitflags = "1.1.0";
    cfg_if = "0.1.9";
    libc = "0.2.60";
    void = "1.0.2";
  };
  deps.nodrop."0.1.13" = {};
  deps.notify_rust."3.6.0" = {
    dbus = "0.6.5";
    mac_notification_sys = "0.3.0";
  };
  deps.num_integer."0.1.41" = {
    num_traits = "0.2.8";
    autocfg = "0.1.5";
  };
  deps.num_traits."0.2.8" = {
    autocfg = "0.1.5";
  };
  deps.num_cpus."1.10.1" = {
    libc = "0.2.60";
  };
  deps.objc."0.2.6" = {
    malloc_buf = "0.0.6";
  };
  deps.objc_foundation."0.1.1" = {
    block = "0.1.6";
    objc = "0.2.6";
    objc_id = "0.1.1";
  };
  deps.objc_id."0.1.1" = {
    objc = "0.2.6";
  };
  deps.owning_ref."0.4.0" = {
    stable_deref_trait = "1.1.1";
  };
  deps.parking_lot."0.7.1" = {
    lock_api = "0.1.5";
    parking_lot_core = "0.4.0";
  };
  deps.parking_lot_core."0.4.0" = {
    rand = "0.6.5";
    smallvec = "0.6.10";
    rustc_version = "0.2.3";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.perf_checkup."0.1.0" = {
    derive_more = "0.15.0";
    futures_preview = "0.3.0-alpha.17";
    heim = "0.0.5";
    lazy_static = "1.3.0";
    notify_rust = "3.6.0";
    regex = "1.2.0";
    runtime = "0.3.0-alpha.6";
    snafu = "0.4.3";
  };
  deps.pin_utils."0.1.0-alpha.4" = {};
  deps.pkg_config."0.3.14" = {};
  deps.platforms."0.2.0" = {};
  deps.proc_macro2."0.4.30" = {
    unicode_xid = "0.1.0";
  };
  deps.quote."0.6.13" = {
    proc_macro2 = "0.4.30";
  };
  deps.rand."0.6.5" = {
    rand_chacha = "0.1.1";
    rand_core = "0.4.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_jitter = "0.1.4";
    rand_os = "0.1.3";
    rand_pcg = "0.1.2";
    rand_xorshift = "0.1.1";
    autocfg = "0.1.5";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.rand_chacha."0.1.1" = {
    rand_core = "0.3.1";
    autocfg = "0.1.5";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.1";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rand_jitter."0.1.4" = {
    rand_core = "0.4.0";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.rand_os."0.1.3" = {
    rand_core = "0.4.0";
    rdrand = "0.4.0";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.60";
    winapi = "0.3.7";
  };
  deps.rand_pcg."0.1.2" = {
    rand_core = "0.4.0";
    autocfg = "0.1.5";
  };
  deps.rand_xorshift."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.raw_cpuid."6.1.0" = {
    bitflags = "1.1.0";
    cc = "1.0.38";
    rustc_version = "0.2.3";
  };
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.56" = {};
  deps.redox_users."0.3.0" = {
    argon2rs = "0.2.5";
    failure = "0.1.5";
    rand_os = "0.1.3";
    redox_syscall = "0.1.56";
  };
  deps.regex."1.2.0" = {
    aho_corasick = "0.7.4";
    memchr = "2.2.1";
    regex_syntax = "0.6.10";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.3";
  };
  deps.regex_syntax."0.6.10" = {
    ucd_util = "0.1.5";
  };
  deps.romio."0.3.0-alpha.9" = {
    async_datagram = "3.0.0";
    async_ready = "3.0.0";
    crossbeam_utils = "0.6.6";
    futures_preview = "0.3.0-alpha.17";
    lazy_static = "1.3.0";
    libc = "0.2.60";
    log = "0.4.7";
    mio = "0.6.19";
    mio_uds = "0.6.7";
    num_cpus = "1.10.1";
    parking_lot = "0.7.1";
    slab = "0.4.2";
  };
  deps.runtime."0.3.0-alpha.6" = {
    futures_preview = "0.3.0-alpha.17";
    runtime_attributes = "0.3.0-alpha.5";
    runtime_native = "0.3.0-alpha.5";
    runtime_raw = "0.3.0-alpha.4";
  };
  deps.runtime_attributes."0.3.0-alpha.5" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
  };
  deps.runtime_native."0.3.0-alpha.5" = {
    futures_preview = "0.3.0-alpha.17";
    runtime_raw = "0.3.0-alpha.4";
    async_datagram = "2.2.0";
    futures_timer = "0.2.1";
    juliex = "0.3.0-alpha.7";
    lazy_static = "1.3.0";
    romio = "0.3.0-alpha.9";
    wasm_bindgen = "0.2.48";
    wasm_bindgen_futures = "0.3.25";
  };
  deps.runtime_raw."0.3.0-alpha.4" = {
    futures_preview = "0.3.0-alpha.17";
  };
  deps.rustc_demangle."0.1.15" = {};
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.scoped_threadpool."0.1.9" = {};
  deps.scopeguard."0.3.3" = {};
  deps.scopeguard."1.0.0" = {};
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.slab."0.4.2" = {};
  deps.smallvec."0.6.10" = {};
  deps.snafu."0.4.3" = {
    backtrace = "0.3.33";
    doc_comment = "0.3.1";
    snafu_derive = "0.4.3";
  };
  deps.snafu_derive."0.4.3" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
  };
  deps.stable_deref_trait."1.1.1" = {};
  deps.syn."0.15.42" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    unicode_xid = "0.1.0";
  };
  deps.synstructure."0.10.2" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
    unicode_xid = "0.1.0";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.time."0.1.42" = {
    libc = "0.2.60";
    redox_syscall = "0.1.56";
    winapi = "0.3.7";
  };
  deps.ucd_util."0.1.5" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.utf8_ranges."1.0.3" = {};
  deps.void."1.0.2" = {};
  deps.wasm_bindgen."0.2.48" = {
    wasm_bindgen_macro = "0.2.48";
  };
  deps.wasm_bindgen_backend."0.2.48" = {
    bumpalo = "2.5.0";
    lazy_static = "1.3.0";
    log = "0.4.7";
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
    wasm_bindgen_shared = "0.2.48";
  };
  deps.wasm_bindgen_futures."0.3.25" = {
    futures = "0.1.28";
    js_sys = "0.3.25";
    wasm_bindgen = "0.2.48";
  };
  deps.wasm_bindgen_macro."0.2.48" = {
    quote = "0.6.13";
    wasm_bindgen_macro_support = "0.2.48";
  };
  deps.wasm_bindgen_macro_support."0.2.48" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.13";
    syn = "0.15.42";
    wasm_bindgen_backend = "0.2.48";
    wasm_bindgen_shared = "0.2.48";
  };
  deps.wasm_bindgen_shared."0.2.48" = {};
  deps.widestring."0.4.0" = {};
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.ws2_32_sys."0.2.1" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
}
